version: '3.9'

services:
  pgvector:
    image: pgvector/pgvector:0.6.0-pg16
    container_name: pgvector
    environment:
      POSTGRES_PASSWORD: ${PGVECTOR_DB_PASSWORD}
      POSTGRES_USER: ${PGVECTOR_DB_USER}
      POSTGRES_DB: ${PGVECTOR_DB_NAME}
    ports:
      - ${PGVECTOR_PORT}:5432
    volumes:
      - pgvector_data:/var/lib/postgresql/data
      - ./data:/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - pgvector
    restart: unless-stopped

volumes:
  pgvector_data:
